services:
  website:
    build: .
    ports:
      - "8080:8080"
    # To enable live reloading of content when drafting posts, we mount the local blog content directory
    volumes:
      - ./website:/app/website
    # The default command rebuilds the site and starts the server
    command: >
      sh -c "python website/build_site.py && python -m http.server 8080 -d website/public"
